// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apptypes} from '../models';

export function CheckServer(arg1:string):Promise<apptypes.ServerStatus>;

export function ConfigureClaudeCode(arg1:apptypes.ClaudeCodeConfigRequest):Promise<apptypes.Result>;

export function ConfigureCodex(arg1:string):Promise<apptypes.Result>;

export function GetAvailableEditors():Promise<Array<apptypes.Editor>>;

export function GetClaudeCodeModels(arg1:string):Promise<Array<apptypes.ModelOption>>;

export function GetConfigStatus():Promise<apptypes.ConfigStatus>;

export function GetServerURL():Promise<string>;

export function GetTokens():Promise<apptypes.TokenListResponse>;

export function IsLoggedIn():Promise<boolean>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<apptypes.UserInfo>;

export function Logout():Promise<void>;

export function OpenConfigFile(arg1:string,arg2:string):Promise<void>;

export function RevealTokenKey(arg1:number):Promise<string>;

export function UninstallCCSwitch():Promise<apptypes.Result>;
