// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckServer(arg1) {
  return window['go']['main']['App']['CheckServer'](arg1);
}

export function ConfigureClaudeCode(arg1) {
  return window['go']['main']['App']['ConfigureClaudeCode'](arg1);
}

export function ConfigureCodex(arg1) {
  return window['go']['main']['App']['ConfigureCodex'](arg1);
}

export function GetAvailableEditors() {
  return window['go']['main']['App']['GetAvailableEditors']();
}

export function GetClaudeCodeModels(arg1) {
  return window['go']['main']['App']['GetClaudeCodeModels'](arg1);
}

export function GetCodexModels(arg1) {
  return window['go']['main']['App']['GetCodexModels'](arg1);
}

export function GetConfigStatus() {
  return window['go']['main']['App']['GetConfigStatus']();
}

export function GetLaunchContext() {
  return window['go']['main']['App']['GetLaunchContext']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function GetTokens() {
  return window['go']['main']['App']['GetTokens']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function ListConfigFiles() {
  return window['go']['main']['App']['ListConfigFiles']();
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenConfigEditorWindow(arg1) {
  return window['go']['main']['App']['OpenConfigEditorWindow'](arg1);
}

export function OpenConfigFile(arg1, arg2) {
  return window['go']['main']['App']['OpenConfigFile'](arg1, arg2);
}

export function ReadConfigFile(arg1) {
  return window['go']['main']['App']['ReadConfigFile'](arg1);
}

export function RevealTokenKey(arg1) {
  return window['go']['main']['App']['RevealTokenKey'](arg1);
}

export function SaveConfigFile(arg1) {
  return window['go']['main']['App']['SaveConfigFile'](arg1);
}

export function UpdateServerURL(arg1) {
  return window['go']['main']['App']['UpdateServerURL'](arg1);
}
